### ISSUE TITLE
GUIDs break the RPC icons

### ISSUE THREAD

**Issue by sudokoko** [LBPUnion/PLRPC#10]
**Describe the bug**
When a slot/user icon is a GUID, the RPC status displays a broken image icon.

**To Reproduce**
1. Start the RPC client
2. Go into a level with no icon, i.e. https://beacon.lbpunion.com/slot/12842
3. Wait for RPC to update

**Expected behavior**
Currently there is no 'expected' behavior, we need to implement better icon handling at some point. Probably when a few new icon renders for other slot types are made.

**Screenshots**
![image](https://user-images.githubusercontent.com/68549366/232352052-8d76d615-f176-4747-ad07-3a975420c1e4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version or Commit Hash: Development Build 5ac28e80a5930ac0b03cc5097e3ebd13521ccd2a

**Comment by speedyman09** [comment]
I think that some sort of handling should be implemented in lighthouse. If an icon for a level that does not have an icon is requested, the server should send a placeholder icon.

**Comment by sudokoko** [comment]
> If an icon for a level that does not have an icon is requested using the API, the server should send a placeholder icon.

We were discussing potentially adding this. @Slendy thoughts?

**Comment by sudokoko** [comment]
> I think it should be up to the consumer of the api to handle missing/guid resources rather than the server itself.

I agree with this. Since this is generally targeted towards Beacon players, it shouldn't be much of an issue but something I'd still like to work at.

**Comment by speedyman09** [comment]
also, is it possible to add CORS support to the lighthouse API controller, so browsers can fetch data using the API?

**Comment by sudokoko** [comment]
> also, is it possible to add CORS support to the lighthouse API controller, so browsers can fetch data using the API?

Possibly. I'll look into it. Though I've had no issues fetching data directly using a browser.

On another note, closing this issue and merging #11 as is, will revisit the image issue later.
