### ISSUE TITLE
LittleBigPlanet 1 causing issues with client

### ISSUE THREAD

**Issue by cmyk05** [LBPUnion/PLRPC#23]
I have been trying to get this to work and can't really figure out. First and foremost I sincerely apologise if I'm just missing something. In the config.json file i have http://lighthouse.lbpunion.com and my username definitely set correctly, and it's the first time I've not gotten 404 or 403 but when I do so, it connects to my discord fine but then I see a "WARN Failed to get user status from server." and the program just hangs there. If it helps the application ID I've just left as it was when i opened it after trying manual a few times, but I don't seem to be getting any further than this. Any help would be greatly appreciated.

**Comment by sudokoko** [comment]
Thanks for reaching out :)

This error occurs when Beacon is not registering that you're actively online, and in most cases it's because you're not online. However, there can be some discrepancies here. Would you mind sending over your Beacon username so I can check things out?

**Comment by cmyk05** [comment]
Thanks! I shoulda specified, right now I am on LBP1, username is "bonkleg". Thanks for the pointing me to the gui beta though! :)

**Comment by sudokoko** [comment]
> Thanks! I shoulda specified, right now I am on LBP1, username is "bonkleg". Thanks for the pointing me to the gui beta though! :)

No problem :)

This problem seems to be Beacon related, as the server is showing you're online and playing LBP1 but it's not displaying any room information. I'll see if this is LBP1 specific.

```json
{
  "statusType": 1,
  "currentVersion": 0,
  "currentPlatform": 0,
  "currentRoom": null, // this is what is causing the issue
  "lastLogin": 1688675174262,
  "lastLogout": 1688592484164
}
```

**Comment by cmyk05** [comment]
Thanks so much for helping!

**Comment by sudokoko** [comment]
> > Thanks! I shoulda specified, right now I am on LBP1, username is "bonkleg". Thanks for the pointing me to the gui beta though! :)
> 
> No problem :)
> 
> This problem seems to be Beacon related, as the server is showing you're online and playing LBP1 but it's not displaying any room information. I'll see if this is LBP1 specific.

I was not able to replicate this issue, The game created a room on the server for a few testers that I got ahold of a few minutes ago. My best advice I can give at the moment is restarting your game and hoping for the best. Feel free to leave a reply if you're still encountering the issue :)

**Comment by sudokoko** [comment]
So, the reason this is occurring is due to an oversight on my part, LBP1 does not work with rooms by design. Those are only for LBP2 and 3 to facilitate Dive-In. I'll push a fix here within the hour.

**Comment by sudokoko** [comment]
Issue resolved in https://github.com/LBPUnion/PLRPC/commit/359b09956149acf903ae5105d5e5b1dc4922e447.
